services:
  source-db:
    image: postgres:18
    container_name: data-kata-source-db
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_pass
    ports:
      - "5432:5432"
    volumes:
      - ./docker/source-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  soap-mock:
    build: ./docker/soap-mock
    container_name: data-kata-soap-mock
    ports:
      - "8090:8090"
      - "8091:8091"
