spring.application.name=data-kata-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/warehousedb
spring.datasource.username=warehouse_user
spring.datasource.password=warehouse_pass
